# Generated by Django 5.0.6 on 2024-05-08 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acabamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Q', 'Lombada quadrada'), ('C', 'Lombada canoa'), ('R', 'Refile')], default='Q', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campanha', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Papel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=50)),
                ('gramatura', models.IntegerField()),
                ('bobina', models.IntegerField()),
                ('cutoff', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Versao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('1', 'V1'), ('2', 'V2'), ('3', 'V3'), ('4', 'V4'), ('5', 'V5'), ('6', 'V6')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('tiragem', models.IntegerField()),
                ('id_acabamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.acabamento')),
                ('id_ciclo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.ciclo')),
                ('id_versao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.versao')),
            ],
        ),
        migrations.CreateModel(
            name='Caderno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('paginacao', models.IntegerField()),
                ('desp_acerto_interno', models.FloatField()),
                ('desp_impressao_interno', models.FloatField()),
                ('desp_acbto_interno', models.FloatField()),
                ('desp_acerto_cliente', models.FloatField()),
                ('desp_impressao_cliente', models.FloatField()),
                ('desp_acbto_cliente', models.FloatField()),
                ('papel_bruto_interno', models.FloatField()),
                ('papel_bruto_cliente', models.FloatField()),
                ('id_papel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.papel')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.produto')),
            ],
        ),
    ]
